apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth-service
  name: auth-service
  namespace: moonpay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  strategy: {}
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - image: auth-service
          name: auth-service
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-service
  name: auth-service
  namespace: moonpay
spec:
  ports:
    - name: 8081-50051
      port: 8081
      protocol: TCP
      targetPort: 50051
  selector:
    app: auth-service
  type: ClusterIP
