apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-gateway
  name: api-gateway
  namespace: moonpay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  strategy: {}
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - image: api-gateway
          name: api-gateway
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          envFrom:
            - secretRef:
                name: api-gateway-service-secrets

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway-service
  name: api-gateway-service
  namespace: moonpay
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: api-gateway-service
  type: NodePort
status:
  loadBalancer: {}
